"""add document processing ownership

Revision ID: 9e117ff4c2f2
Revises: cec168da05c0
Create Date: 2026-08-19 16:08:45.429156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e117ff4c2f2'
down_revision: Union[str, Sequence[str], None] = 'cec168da05c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_worker_id', sa.UUID(), nullable=True))
    op.add_column('documents', sa.Column('processing_lease_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_lease_expiry')
    op.drop_column('documents', 'processing_worker_id')
    # ### end Alembic commands ###
